project_id_env: CROWDIN_PROJ_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true

files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/%android_code%/%original_file_name%
    type: android