name: Android CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Kanging jks
      run: echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release_key.jks
  
    - name: Kanging env pass
      run: |
          echo "$KEYSTORE_PASSWORD" > mypass.txt
          echo "$KEY_ALIAS" > myalias.txt
          chmod +x uploadtg.sh
    - name: Build with Gradle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: upload to tg
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: Dualboot Helper
      run: |
        if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          bash $GITHUB_WORKSPACE/uploadtg.sh release_key.jks
          bash $GITHUB_WORKSPACE/uploadtg.sh myalias.txt
          bash $GITHUB_WORKSPACE/uploadtg.sh mypass.txt
        else
          echo "Telegram bot token is undefined, please add it to repository secrets!"
          exit 1
        fi
